### ISSUE TITLE
Can I get a picture of interior of the Software

### ISSUE THREAD

**Issue by Joculant** [kkiyama117/MVMKR#11]
Can I please get a picture of the interior of the Software

Here is my email- helpingpeoples10@gmail.com

**Comment by kkiyama117** [comment]
@Joculant 
I'm sorry but I'm unable to understand what you mean for my lackness of skill to read English. I don't recognize what you need is `structure of software` or `picture(or screenshot) rendered at electron window` or anything else.  Would you explain what you need for me?

And I'm afraid I can't tell you this program's structure because this program is still in progress (almost all things is not done) and I'm busy writing other programs, but I can tell you what libraries are used in current master branch or what I planned to implement. So, I think I can provide what you need if I understand what is needed.

**Comment by Joculant** [comment]
picture(or screenshot) rendered at electron window

**Comment by kkiyama117** [comment]
Thanks so much for your reply.
This program is genereted from https://github.com/electron-react-boilerplate/electron-react-boilerplate, which uses electron and [react](https://reactjs.org/), and `app` folder is only needed for rendering react site so that you may see react components  by running `npm run start`. you also run `npm run start` at root folder.

But this repo is too old to run with recent NodeJS (at least it doesn't run on `manjaro linux` machine and `NodeJS` 14.8.0) and I think some of this code is deplecated or not recommended. 
I may be able to fix this repo because I was done nothing without few trial related to react and redux, but I think coding from the beginning is better way than fix this repository.

My recommendation is to access [electron-react-boilerplate](https://github.com/electron-react-boilerplate/electron-react-boilerplate) and generate new repository with `use this template` button, and run it, based on newer packages than this repo's ones. Maybe I can help your running this boilerplate so Let me know if you need.

**Comment by Joculant** [comment]
Yes, I need one.............please do send me over

**Comment by kkiyama117** [comment]
Sure. At first, I need to know about you and environment you have because correct advise is depending on the situation. Please tell me below tools exist in your pc (and you can use, if exist) or not.

- `git`
- `NodeJS` (with `npm` or `yarn`)

If you make these tools available for running on your PC, only you need to do is create new repo from boilerplate I introduced and run it on your PC.

**Comment by Joculant** [comment]
So I really don't have any idea about coding so I will rather want you to
make me an Exe. file so that I can directly download it.

**Comment by kkiyama117** [comment]
This program is only demo and almost the same as sample on electron-react-boilerplate. so you get useless one even if you get `exe` version (because you only get the same one generated from that boilerplate). 
Do you plan to develop or create video editor, or only want to use completed product? If you don't feel like writing code, you should use free or proprietary software like [`adobe premire pro`](https://www.adobe.com/products/premiere.html?promoid=PQ7SQBYQ&mv=other) or introduced ones at https://www.oberlo.com/blog/best-free-video-editing-software.

**Comment by Joculant** [comment]
No I want a software for my website so that I can give the member of my
website blog free Video editor software as they qant from me.

**Comment by kkiyama117** [comment]
I'm sorry but it is no use giving this program for your follower, and if you do so, you may lose someone's trust because this is ONLY DEMO AND ALMOST THE SAME AS SAMPLE ON THE BOILERPLATE, which is not a video editor but a desktop program with `react`, library to render javascript on webpage.  If you need to get programs available to use, please try another one.

**Comment by Joculant** [comment]
Ok man I appreciate you.  Thank u for coporating.
